name: candy_sorter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_riverpod: ^1.0.3
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.0.13
  get_it: ^7.1.4
  confetti: ^0.6.0
  liquid_progress_indicator: ^0.4.0
  lottie: ^1.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bowl.svg
    - assets/candy.svg
    - assets/cup.png
    - assets/me.png
    - assets/candies.json
